export enum AuthErrorCode {
  ACCOUNT_ID_ALREADY_EXISTS = 'ACCOUNT_ID_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_TEMPORARILY_LOCKED = 'ACCOUNT_TEMPORARILY_LOCKED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG = 'PASSWORD_TOO_LONG',
  PASSWORD_MISSING_LOWERCASE = 'PASSWORD_MISSING_LOWERCASE',
  PASSWORD_MISSING_NUMBER = 'PASSWORD_MISSING_NUMBER',
  PASSWORD_MISSING_SPECIAL_CHAR = 'PASSWORD_MISSING_SPECIAL_CHAR',
  INVALID_ACCOUNT_ID_LENGTH = 'INVALID_ACCOUNT_ID_LENGTH',
  INVALID_ACCOUNT_ID_FORMAT = 'INVALID_ACCOUNT_ID_FORMAT',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  NAME_REQUIRED = 'NAME_REQUIRED',
  NAME_TOO_LONG = 'NAME_TOO_LONG',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

const AUTH_ERROR_CODES = new Set<string>(Object.values(AuthErrorCode));

export function isAuthErrorCode(value: string): value is AuthErrorCode {
  return AUTH_ERROR_CODES.has(value);
}
